spring:
  datasource:
    url: jdbc:h2:mem:medical-facility
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
flyway:
  user: sa
  password: password
  schemas: med-facility
  url: jdbc:h2:mem:medical-facility